# Smakemake file for running BUSCO3.
# Run command '$ snakemake run_4' to run analysis on example data 4.fa
# Change to transcriptome by adding --config mode=transcriptome
# Parameters can be changed by changing config.json


configfile: "config.json"
mode = config["mode"]
lineage = config["lineage"]
rule busco_ann:
    input:
        "../Data/{sample}.fa"
    output:
        directory("run_{sample}")
    shell:
        "python ~/miniconda3/bin/run_BUSCO.py -i {input} -l {lineage} -o {wildcards.sample} -m {mode}"
