# Smakemake file for running BUSCO3.
# Run command '$ snakemake run_4' to run analysis on example data 4.fa
# Change to transcriptome by adding --config mode=transcriptome
# Parameters can be changed by changing config.json

 
configfile: "config.json"
mode = config["mode"]
rule busco_ann:
    input:
        "Data/{sample}.fa"
    output:
        directory("run_{sample}")
    shell:
        "python ~/miniconda3/bin/run_BUSCO.py -i {input} -l /home/hampus/miniconda3/pkgs/busco-3.0.2-py36_8/eukaryota_odb9/ -o {wildcards.sample} -m {mode}"
