# Execute with: snakemake ../data/intermediate/[run_name]_sorted.bam ../data/intermediate/run_[run_name]

rule all:
    input:
        "../data/intermediate/{sample}_mapped.bam",
        "../data/intermediate/run_{sample}",
        "../data/intermediate/trinity"

include: "bowtie2"
include: "busco"
include: "trinity"
